// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica.Server.Models;

#nullable disable

namespace krat1.Server.Migrations
{
    [DbContext(typeof(KratosContext))]
    [Migration("20250521200243_DbKratos")]
    partial class DbKratos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krat1.Server.Models.Kratos.ActividadEconomicas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo_ciiu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("ActividadEconomicas");
                });

            modelBuilder.Entity("Krat1.Server.Models.Kratos.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("empresaId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("empresaId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Categorias", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("actualizado_en")
                        .HasColumnType("datetime2");

                    b.Property<int>("categoriaPadre")
                        .HasColumnType("int");

                    b.Property<DateTime>("creado_en")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("categoriaPadre");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Empresas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("actividadId")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("actualizado_en")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("creado_en")
                        .HasColumnType("datetime2");

                    b.Property<string>("dv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombreComercial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("razonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("regimenId")
                        .HasColumnType("int");

                    b.Property<string>("representanteLegal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tiposociedadId")
                        .HasColumnType("int");

                    b.Property<int>("token")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("actividadId");

                    b.HasIndex("regimenId");

                    b.HasIndex("tiposociedadId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Impuestos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("actividadId")
                        .HasColumnType("int");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("porcentaje")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("regimenId")
                        .HasColumnType("int");

                    b.Property<int>("sociedadesId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("actividadId");

                    b.HasIndex("regimenId");

                    b.HasIndex("sociedadesId");

                    b.ToTable("Impuestos");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Inventarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("actualizado_en")
                        .HasColumnType("datetime2");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("creado_en")
                        .HasColumnType("datetime2");

                    b.Property<int>("productoId")
                        .HasColumnType("int");

                    b.Property<int>("puntoVentaId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("productoId");

                    b.HasIndex("puntoVentaId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Modulos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Permisos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("consultar")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("editar")
                        .HasColumnType("bit");

                    b.Property<bool>("eliminar")
                        .HasColumnType("bit");

                    b.Property<bool>("exportar")
                        .HasColumnType("bit");

                    b.Property<bool>("importar")
                        .HasColumnType("bit");

                    b.Property<bool>("insertar")
                        .HasColumnType("bit");

                    b.Property<bool>("leer")
                        .HasColumnType("bit");

                    b.Property<string>("moduloId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("modulosId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("rolesId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("modulosId");

                    b.HasIndex("rolesId");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Productos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Impuesto")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("actualizado_en")
                        .HasColumnType("datetime2");

                    b.Property<int>("categoria")
                        .HasColumnType("int");

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<string>("costo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("creado_en")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("precio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("stockMinimo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("Impuesto");

                    b.HasIndex("categoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.PuntoVentas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("actualizado_en")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("creado_en")
                        .HasColumnType("datetime2");

                    b.Property<string>("direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("ResponsableId");

                    b.ToTable("PuntoVentas");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.RegimenesTributarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("RegimenesTributarios");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.TiposSociedades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposSociedades");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.TratamientosEmpresas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("empresaId")
                        .HasColumnType("int");

                    b.Property<string>("porcentaje")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("tipoImpuesto")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("empresaId");

                    b.HasIndex("tipoImpuesto");

                    b.ToTable("TratamientosEmpresas");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("actualizado_en")
                        .HasColumnType("datetime2");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("creado_en")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("rolesId")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("rolesId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Krat1.Server.Models.Kratos.Roles", b =>
                {
                    b.HasOne("krat1.Server.Models.Kratos.Empresas", "rolempresaId")
                        .WithMany()
                        .HasForeignKey("empresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("rolempresaId");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Categorias", b =>
                {
                    b.HasOne("krat1.Server.Models.Kratos.Categorias", "categoriaPadre_fk")
                        .WithMany()
                        .HasForeignKey("categoriaPadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("categoriaPadre_fk");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Empresas", b =>
                {
                    b.HasOne("Krat1.Server.Models.Kratos.ActividadEconomicas", "empresaActividad_fk")
                        .WithMany()
                        .HasForeignKey("actividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("krat1.Server.Models.Kratos.RegimenesTributarios", "empresaRegimen_fk")
                        .WithMany()
                        .HasForeignKey("regimenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("krat1.Server.Models.Kratos.TiposSociedades", "empresaSociedad_fk")
                        .WithMany()
                        .HasForeignKey("tiposociedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("empresaActividad_fk");

                    b.Navigation("empresaRegimen_fk");

                    b.Navigation("empresaSociedad_fk");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Impuestos", b =>
                {
                    b.HasOne("Krat1.Server.Models.Kratos.ActividadEconomicas", "impuestoActividad_fk")
                        .WithMany()
                        .HasForeignKey("actividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("krat1.Server.Models.Kratos.RegimenesTributarios", "impuestoRegimen_fk")
                        .WithMany()
                        .HasForeignKey("regimenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("krat1.Server.Models.Kratos.TiposSociedades", "impuestoSociedades_fk")
                        .WithMany()
                        .HasForeignKey("sociedadesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("impuestoActividad_fk");

                    b.Navigation("impuestoRegimen_fk");

                    b.Navigation("impuestoSociedades_fk");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Inventarios", b =>
                {
                    b.HasOne("krat1.Server.Models.Kratos.Productos", "producto_fk")
                        .WithMany()
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("krat1.Server.Models.Kratos.PuntoVentas", "puntoVenta_fk")
                        .WithMany()
                        .HasForeignKey("puntoVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("producto_fk");

                    b.Navigation("puntoVenta_fk");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Permisos", b =>
                {
                    b.HasOne("krat1.Server.Models.Kratos.Modulos", "permisosmodulosId")
                        .WithMany()
                        .HasForeignKey("modulosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Krat1.Server.Models.Kratos.Roles", "permisosrolesId")
                        .WithMany()
                        .HasForeignKey("rolesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("permisosmodulosId");

                    b.Navigation("permisosrolesId");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Productos", b =>
                {
                    b.HasOne("krat1.Server.Models.Kratos.TratamientosEmpresas", "tratamiento_fk")
                        .WithMany()
                        .HasForeignKey("Impuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("krat1.Server.Models.Kratos.Categorias", "categoria_fk")
                        .WithMany()
                        .HasForeignKey("categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("categoria_fk");

                    b.Navigation("tratamiento_fk");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.PuntoVentas", b =>
                {
                    b.HasOne("krat1.Server.Models.Kratos.Usuarios", "usuario_fk")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("usuario_fk");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.TratamientosEmpresas", b =>
                {
                    b.HasOne("krat1.Server.Models.Kratos.Empresas", "empresa_fk")
                        .WithMany()
                        .HasForeignKey("empresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("krat1.Server.Models.Kratos.Impuestos", "impuestos_fk")
                        .WithMany()
                        .HasForeignKey("tipoImpuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("empresa_fk");

                    b.Navigation("impuestos_fk");
                });

            modelBuilder.Entity("krat1.Server.Models.Kratos.Usuarios", b =>
                {
                    b.HasOne("Krat1.Server.Models.Kratos.Roles", "usuariosrolesId")
                        .WithMany()
                        .HasForeignKey("rolesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("usuariosrolesId");
                });
#pragma warning restore 612, 618
        }
    }
}
